import ReduxProvider from "@/redux/provider";
import "./globals.css";
import { Inter } from "next/font/google";
import ColorThemeProvider from "@/mui-components/ColorThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          {/* <ColorThemeProvider>{children}</ColorThemeProvider> */}
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
